#!/bin/sh

if ! [ -f g2t.jar ];
then
	echo "Please run ./build before making the package."
	exit
fi

rm -rf package

mkdir -p package/DEBIAN
mkdir -p package/usr/local/bin
cp g2t.jar package/usr/local/bin

echo "#!/bin/sh" >> package/usr/local/bin/g2t
echo java -jar /usr/local/bin/g2t.jar \$@ >> package/usr/local/bin/g2t

echo Package: g2t >> package/DEBIAN/control
echo Version: 3.1.0 >> package/DEBIAN/control
echo Maintainer: Noa Senesi >> package/DEBIAN/control
echo Architecture: all >> package/DEBIAN/control
echo Description: Grammar2Table >> package/DEBIAN/control

echo "#!/bin/sh" >> package/DEBIAN/postinst
echo chmod 755 /usr/local/bin/g2t >> package/DEBIAN/postinst

chmod -R 755 package

dpkg-deb --build package g2t.deb

